/** Slugs mit interaktiver React-Implementierung (server + client nutzbar). */
export const BUILTIN_EXERCISE_SLUGS = new Set([
  'index',
  'netto-brutto',
  'menue',
  'multiplikationsfunktion',
  'multiplikation-umleitung',
  'multiplikation',
  'multiplikationstabelle-ow',
  'asso-array',
  'elementeanzahl',
  'oop',
  'erase',
  'testentity',
  'farbcode',
  'fileupload',
  'getpostrequest',
  'nutzerprofil',
  'obstgemuese',
  'obstgemuese-abfr',
  'phpinfo',
  'server',
  'buecheranzeige',
  'buechererfassung',
  'pdotest',
  'galerie',
  'galerie-upload',
  'galerie-sql',
  'galerie-reset',
  'news-test',
  'news-newdb',
  'news-sql',
  'news-kategorien',
  'news-ereignisse',
  'news-bilder',
  'json-uebungen',
  'exer-11',
  'exer-12',
  'exer-13',
  'exer-14',
  'exer-15',
  'exer-16',
  'exer-17',
  'exer-18',
])

export function hasBuiltinExercise(slug: string): boolean {
  return BUILTIN_EXERCISE_SLUGS.has(slug)
}
